### ISSUE TITLE
expertise input issue

### ISSUE THREAD

**Issue by MattWiener** [EHDEN/ApplicationPortals#12]
1.  In the section where we ask about familiarity with healthcare databases,   It says "which databases have you worked with", which is fine, though we might want to create checkboxes and then a space for other.   

2.  The next question, "what WAS your familiarity with the data's structure and content" should be "what IS your familiarity" - now that they've done the project (and even now that people may have moved on).

3.  Where it says:  "In which languages, in written or verbal communication internally and external to your organization, does your company operate in?"   should read something more like  "Which languages does your company routinely use for written or oral communication, within your company and with others?"   Sounds much more natural (to my ear, anyway - Nigel, what do you think?).

4.  Why are we asking about web application development?  How is that relevant to translations?

5.  Can we combine the questions about database platforms and database programming?   And are there actually languages for databases other than SQL?   What would familiarity with a database platform mean without the ability to program?

6.  I would add python and R to the programming language question along with C and Java, and not have a separate section about statistical programming to reduce complexity.

7.   Where we ask "What was your role in performing data management or statistical analysis using these terminologies?", we might want to say "performing data management, TRANSFORMATION into other structures, or statistical analysis".

**Comment by PRijnbeek** [comment]
Thanks for all this input. Do note this test round is about the functionality of the tool we are not iterating back to form field discussion (see forum for that).

Nevertheless see response and changes made below:

1. No, this list will be long and not useful to pre-specify i think. Free text field is fine they can provide a list.

2. Agree and changed

3. Changed, but was proposed as is in forum earlier. 

4. Because we want to see if they could play a role later in developing tools as well. It is not a requirement of selection.

5. Familiarity with a DBMS is something else than SQL in that language, it also refers to knowledge about installing the DBMS etc. There are SQL dialects.

6. Well we could off course, but do not see a big problem with this. It does not hurt the make the distinction either, since it asks if they used R and Python for statistical programming. You can use Python for example for different things (web services etc).

7. Agree. Changed.

**Comment by PRijnbeek** [comment]
All answered above. Closed, please re-open if there are problems with the replies.
