### ISSUE TITLE
Internet Address in Applicant Details

### ISSUE THREAD

**Issue by toeresin** [EHDEN/ApplicationPortals#8]
What should be entered here?

 I would suggest to remove it.

**Comment by PRijnbeek** [comment]
It could be a profile page on the company website, but agree it is somewhat vague. We could skip it. Or we add a help text below to clarify?

**Comment by toeresin** [comment]
My proposal would be to skip it. What would be benefit to collect that information of an individual of a company?

**Comment by PRijnbeek** [comment]
Do not disagree with you, but it could provide us insight who we are dealing with, same argument holds for the LinkedIn.

Note we have finalised this discussion in this forum end of January:

https://forum.ehden.eu/t/step-1-all-fields-that-an-applicant-needs-to-enter-while-completing-their-profile/241/6

I like to avoid we iterate back to field discussions too much at this point. This test is mainly on the process using the application tool.

For this specific example, i suggest we add a help text to the form since it was not clear enough for you. It is an optional field anyway.

**Comment by PRijnbeek** [comment]
Changed by help text
